const level1 = new Level(
        [
            new Chicken(),
            new Chicken(),
            new Chick(),
            new Chicken(),
            new Chicken(),
            new Chick(),
            new Chicken(),
            new Chicken(),
            new Chick(),
            new Chicken(),
            new Chicken(),
            new Chick(),
            new Chicken(),
            new Chicken(),
            new Chick(),
            new Chicken(),
            new Chicken(),
            new Chick(),
            new Chicken(),
            new Chicken(),
            new Chick(),
            new Chicken(),
            new Chicken(),
            new Chick()
        ],
        [
            
           
        ],
        [
            new Clouds('./img/5.Fondo/Capas/4.nubes/1.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/2.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/1.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/2.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/1.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/2.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/1.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/2.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/1.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/2.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/1.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/2.webp'),
            new Clouds('./img/5.Fondo/Capas/4.nubes/1.webp'),
         
        ],
        [
            new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', -719),
            new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/2.webp', -719),
            new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/2.webp', -719),
            new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/2_1.webp', -719),
    
            new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 0),
            new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/1.webp', 0),
            new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/1.webp', 0),
            new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/1_1.webp', 0),
    
            new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 719),
            new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/2.webp', 719),
            new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/2.webp', 719),
            new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/2_1.webp', 719),
    
            new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 719*2),
            new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/1.webp', 719*2),
            new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/1.webp', 719*2),
            new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/1_1.webp', 719*2),
    
            new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 719*3),
            new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/2.webp', 719*3),
            new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/2.webp', 719*3),
            new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/2_1.webp', 719*3),
    
            new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 719*4),
            new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/1.webp', 719*4),
            new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/1.webp', 719*4),
            new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/1_1.webp', 719*4),
            
            new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 719*5),
            new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/2.webp', 719*5),
            new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/2.webp', 719*5),
            new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/2_1.webp', 719*5),
    
            new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 719*6),
            new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/1.webp', 719*6),
            new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/1.webp', 719*6),
            new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/1_1.webp', 719*6),

            new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 719*7),
            new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/2.webp', 719*7),
            new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/2.webp', 719*7),
            new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/2_1.webp', 719*7),
    
            new BackgroundObject('img/5.Fondo/Capas/5.cielo_1920-1080px.png', 719*8),
            new BackgroundObject('img/5.Fondo/Capas/3.Fondo3/1.webp', 719*8),
            new BackgroundObject('img/5.Fondo/Capas/2.Fondo2/1.webp', 719*8),
            new BackgroundObject('img/5.Fondo/Capas/1.suelo-fondo1/1_1.webp', 719*8)

        ],
        [
            {
                'bottles': [
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada1.webp'),
                    new CollectableObject('img/6.botella/2.Botella_enterrada2.webp')
                ],
    
                'coins': [
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp'),
                    new CollectableObject('img/8.Coin/Moneda1.webp'),
                    new CollectableObject('img/8.Coin/Moneda2.webp')
                ]
            }
        ]
       
    )


